title: Manuel Silva
tagline: data driven

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  #disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-109838834-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Blog', path: 'blog', url: 'index.html'}
- {name: 'Publications', path: 'menu', url: 'publications.html'}
#- {name: 'Contact', path: 'menu', url: 'contact.html'}
- {name: 'Links', path: 'menu', url: 'links.html'}

social:
- {icon: 'github', link: 'https://github.com/mdusilva'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/manuel-silva-5191b5149'}
- {icon: 'envelope', link: 'mailto:madusilva@gmail.com'}
#- {icon: 'rss-square', link: 'feed.xml'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
